### DISCUSSION TITLE
Can't run Criterion on Github Action

### DISCUSSION THREAD

**Discussion by mlbonniec** [Snaipe/Criterion#423] [Q&A]
Hi,
I would like to run Criterion on Github action.
I didn't succeed to install it with apt-get, so I tried with Homebrew, which worked. However, after installing, the criterion path is not find.

Here is my yml file.
```yml
name: Criterion Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Update version
      run: sudo apt-get update
    - name: Install Homebrew
      run: sudo apt-get install build-essential procps curl file git
    - name: Install Criterion
      run: brew install snaipe/soft/criterion
    - name: Build Unit Tests
      run: make unit_tests
    - name: Run Unit Tests
      run: ./unit_tests
```
As you can see, the installation works.
![image](https://user-images.githubusercontent.com/29955402/141689138-a23a4229-bb75-4b02-b484-7aad9b357124.png)

And, here is the "Build Unit Tests" log message.
```
rm -f src/my_printf.o src/utils/my_strlen.o src/utils/my_putnbr.o src/utils/my_putchar.o src/utils/my_putnbr_base.o src/conversions/putchar.o src/conversions/puthex.o src/conversions/putoct.o src/conversions/putstr.o src/conversions/putnbr.o
rm -rf tests/my_printf_string.o tests/my_printf_char.o tests/my_printf_nbr.o
rm -f libmy.a
rm -rf unit_tests
cc -I ./includes -Wall -Wextra   -c -o tests/my_printf_string.o tests/my_printf_string.c
tests/my_printf_string.c:8:10: fatal error: criterion/criterion.h: No such file or directory
    8 | #include <criterion/criterion.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: tests/my_printf_string.o] Error 1
```
Could you help me? Thanks :wink:
